version: "3.8"

services:

  postgres:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: products
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    
  pgadmin:
    image: dpage/pgadmin4:6.10
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "80:80"
    depends_on:
      - postgres