version: "3.8"

x-database-env:
  &database-env
    DATABASE_HOST: 127.0.0.1
    POSTGRES_DB: products
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root

x-pgadmin-env:
  &pgadmin-env
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "root"
  
services:

  postgres:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      <<: *database-env
    
  pgadmin:
    image: dpage/pgadmin4:6.10
    environment:
      <<: *pgadmin-env
    ports:
      - "80:80"
    depends_on:
      - postgres