@hostname = 127.0.0.1
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@apiVersion = v1
### existing product ID to run some tests
@testID = 2  

###
### products api
###

### Return all products in the repo
GET http://{{host}}/api/{{apiVersion}}/products HTTP/1.1
content-type: {{contentType}}

### Get single product id=2 from the repo
GET http://{{host}}/api/{{apiVersion}}/products/{{testID}} HTTP/1.1
content-type: {{contentType}}

### Try to find a non existing product id
GET http://{{host}}/api/{{apiVersion}}/products/1000 HTTP/1.1
content-type: {{contentType}}


### Add a new product to our repository
POST http://{{host}}/api/{{apiVersion}}/products/ HTTP/1.1
content-type: {{contentType}}

{
  "name": "RANDOM Product",
  "price": "99.99"
}

### Update product 2 in our databse
PUT http://{{host}}/api/{{apiVersion}}/products/{{testID}} HTTP/1.1
content-type: {{contentType}}

{
  "name": "Updated Product TWO",
  "description": "awesome product TWO",
  "price": 50
}

### Delete product 2 from our database
DELETE  http://{{host}}/api/{{apiVersion}}/products/{{testID}} HTTP/1.1
content-type: {{contentType}}

